In [1]:
years = list(range(1991, 2023))

In [2]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

In [3]:
import requests

for year in years:
    url = url_start.format(year)
    data = requests.get(url)
    
    with open("mvp/{}.html".format(year), "w+", encoding = "utf-8") as f:
              f.write(data.text)

In [4]:
from bs4 import BeautifulSoup

In [5]:
with open("mvp/1991.html", encoding = "utf-8") as f:
    page = f.read()

In [6]:
soup = BeautifulSoup(page, "html.parser")

In [7]:
soup.find('tr', class_='over_header').decompose()

In [8]:
mvp_table = soup.find_all(id = "mvp")

In [9]:
import pandas as pd

In [10]:
mvp_1991 = pd.read_html(str(mvp_table))[0]

In [16]:
pd.read_html(str(mvp_table))[0]

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Giannis Antetokounmpo,25,MIL,85.0,962.0,1010,0.952,63,30.4,29.5,13.6,5.6,1.0,1.0,0.553,0.304,0.633,11.1,0.279
1,2,LeBron James,35,LAL,16.0,753.0,1010,0.746,67,34.6,25.3,7.8,10.2,1.2,0.5,0.493,0.348,0.693,9.8,0.204
2,3,James Harden,30,HOU,0.0,367.0,1010,0.363,68,36.5,34.3,6.6,7.5,1.8,0.9,0.444,0.355,0.865,13.1,0.254
3,4,Luka Dončić,20,DAL,0.0,200.0,1010,0.198,61,33.6,28.8,9.4,8.8,1.0,0.2,0.463,0.316,0.758,8.8,0.207
4,5,Kawhi Leonard,28,LAC,0.0,168.0,1010,0.166,57,32.4,27.1,7.1,4.9,1.8,0.6,0.470,0.378,0.886,8.7,0.226
5,6,Anthony Davis,26,LAL,0.0,82.0,1010,0.081,62,34.4,26.1,9.3,3.2,1.5,2.3,0.503,0.330,0.846,11.1,0.250
6,7,Chris Paul,34,OKC,0.0,26.0,1010,0.026,70,31.5,17.6,5.0,6.7,1.6,0.2,0.489,0.365,0.907,8.9,0.193
7,8,Damian Lillard,29,POR,0.0,23.0,1010,0.023,66,37.5,30.0,4.3,8.0,1.1,0.3,0.463,0.401,0.888,11.6,0.225
8,9,Nikola Jokić,24,DEN,0.0,18.0,1010,0.018,73,32.0,19.9,9.7,7.0,1.2,0.6,0.528,0.314,0.817,9.8,0.202
9,10,Pascal Siakam,25,TOR,0.0,17.0,1010,0.017,60,35.2,22.9,7.3,3.5,1.0,0.9,0.453,0.359,0.792,5.4,0.123
10,11,Jimmy Butler,30,MIA,0.0,9.0,1010,0.009,58,33.8,19.9,6.7,6.0,1.8,0.6,0.455,0.244,0.834,9.0,0.221
11,12,Jayson Tatum,21,BOS,0.0,1.0,1010,0.001,66,34.3,23.4,7.0,3.0,1.4,0.9,0.450,0.403,0.812,6.9,0.146

In [12]:
dfs = []
for year in years:
    with open("mvp/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_='over_header').decompose()
    mvp_table = soup.find_all(id = "mvp")
    mvp = pd.read_html(str(mvp_table))[0]
    mvp["Year"] = year
    
    dfs.append(mvp)

AttributeError: 'NoneType' object has no attribute 'decompose'

In [ ]:
mvps = pd.concat(dfs)

In [ ]:
mvps

In [ ]:
mvps.to_csv("mvps.csv")

In [ ]:
from selenium import webdriver

In [ ]:
import timedriver = webdriver.Chrome(executable_path = "C:/Users/aniqp/Documents/chromedriver_win32/chromedriver.exe")

In [ ]:
import time

player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

year = 1991
url = player_stats_url.format(1991)

driver.get(url)
driver.execute_script("window.scrollTo(1,10000)")
time.sleep(2)

html=driver.page_source

In [ ]:
with open("player/{}.html".format(year), "w+", encoding = "utf-8") as f:
    f.write(html)

In [ ]:
for year in years:
    url = player_stats_url.format(1991)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html=driver.page_source    
    with open("player/{}.html".format(year), "w+", encoding = "utf-8") as f:
        f.write(html)

In [ ]:
dfs = []
for year in years:
    with open("player/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_='thead').decompose()
    player_table = soup.find_all(id = "per_game_stats")
    player = pd.read_html(str(player_table))[0]
    player["Year"] = year
    dfs.append(player)

In [ ]:
players = pd.concat(dfs)

In [ ]:
players

In [ ]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [ ]:
import requests

for year in years:
    url = team_stats_url.format(year)
    data = requests.get(url)

    with open("team/{}.html".format(year), "w+", encoding = "utf-8") as f:
        f.write(data.text)

In [ ]:
dfs = []

for year in years:
    with open("team/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_='thead').decompose()
    team_table = soup.find_all(id = "divs_standings_E")
    team = pd.read_html(str(team_table))[0]
    team["Year"] = year
    team['Team'] = team['Eastern Conference']
    del team['Eastern Conference']
    dfs.append(team)

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_='thead').decompose()
    team_table = soup.find_all(id = "divs_standings_W")
    team = pd.read_html(str(team_table))[0]
    team["Year"] = year
    team['Team'] = team['Western Conference']
    del team['Western Conference']
    dfs.append(team)

In [64]:
teams = pd.concat(dfs)

In [65]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0   56  26  .683     —  111.5  105.7   5.22  1991       Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991   Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991      New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  42  30  .583     —  112.4  110.2   2.26  2021     Dallas Mavericks*
14  38  34  .528   4.0  113.3  112.3   1.07  2021    Memphis Grizzlies*
15  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
16  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
17  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

[1033 rows x 9 columns]

In [67]:
teams.to_csv("teams.csv")